// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import type { PrismaConfig } from "prisma";

export default {
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/run-seeds.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
} satisfies PrismaConfig;
